Two small refineDiag fixes
NOAA-GFDL/MOM6-examples pull request #346
Opened 2021-12-16 22:04 UTC by ceblanton

1. Use basin codes in the "history" file YYYYMMDD.basin_codes.nc if it exists
2. Fix for detecting symmetric mode in history file output

2021-12-17 18:00 UTC, raphaeldussin requested changes

2021-12-17 18:00 UTC, raphaeldussin commented on tools/analysis/refineDiag_ocean_month.py
> +        if x.shape[1] == 1+mask.shape[0]: #symmetric case
I think this should be `x.shape[1] == 1+mask.shape[1]` to test the length along the x-axis

2021-12-17 18:58 UTC, ceblanton commented on tools/analysis/refineDiag_ocean_month.py
> +        if x.shape[1] == 1+mask.shape[0]: #symmetric case
Thanks for taking a look. I believe that `x` and `mask` have different shapes, `x` 3D including time and shape only 2D, so targeting the x axis should be different indexes. e.g. in the test case I have, `x` data variable has a shape of `(12, 1080, 1440)` and `mask` is `(1080, 1440)`.

(This would be a good use for using dimension labels instead of indexes..)

2021-12-20 17:32 UTC, raphaeldussin requested changes

2021-12-20 17:32 UTC, raphaeldussin commented on tools/analysis/refineDiag_ocean_month.py
> +        if x.shape[1] == 1+mask.shape[0]: #symmetric case
ok so then I would try to bulletproof it against 2d or 3d arrays with something that:

```python
assert (len(mask.shape) == 2)
if (x.shape[-2:][1] == 1+mask.shape[1]) and (x.shape[-2:][0] == 1+mask.shape[0]):
```

2022-01-07 15:40 UTC, ceblanton commented on tools/analysis/refineDiag_ocean_month.py
> +        if x.shape[1] == 1+mask.shape[0]: #symmetric case
@raphaeldussin sorry for the delay. I agree completely with your suggested edits to account for 2D or 3D input data and updated the PR.

2022-01-07 15:56 UTC, raphaeldussin approved these changes

2022-01-07 16:00 UTC, marshallward commented
Thanks for this update @ceblanton and also @raphaeldussin for reviewing.

2022-01-07 16:00 UTC, merged